# -*- coding: utf-8 -*-

VALID_GET = "VALID_GET"
INVALID_GET = "INVALID_GET"

VALID_SET = "VALID_SET"
INVALID_SET  = "INVALID_SET"

GET_COMMAND = "get"
SET_COMMAND = "set"

ENCODING = 'utf-8'

INVALID_COMMAND = "INVALID_COMMAND"


INITIAL_STAGE = 'initial'
INTERMEDIATE_STAGE = 'intermediate'
FINAL_STAGE = 'final'


TASK_WORD_COUNT = 'word_count'
TASK_INVERTED_INDEX = 'inverted_index'

DATA_STORE_PORT = 50151