# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import store_pb2 as store__pb2


class GetSetStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.operation = channel.unary_unary(
        '/GetSet/operation',
        request_serializer=store__pb2.Request.SerializeToString,
        response_deserializer=store__pb2.Response.FromString,
        )


class GetSetServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def operation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetSetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'operation': grpc.unary_unary_rpc_method_handler(
          servicer.operation,
          request_deserializer=store__pb2.Request.FromString,
          response_serializer=store__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GetSet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
