# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cworker.proto\"H\n\x0emapper_request\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\r\n\x05lines\x18\x02 \x03(\t\x12\x14\n\x0cmap_function\x18\x03 \x01(\t\"#\n\x05tuple\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"$\n\ntuple_list\x12\x16\n\x06result\x18\x01 \x03(\x0b\x32\x06.tuple\")\n\x0fmapper_response\x12\x16\n\x06result\x18\x01 \x03(\x0b\x32\x06.tuple\"1\n\x07\x61\x64\x64ress\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"#\n\x13\x63onnection_response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"*\n\x10reducer_response\x12\x16\n\x06result\x18\x01 \x03(\x0b\x32\x06.tuple\"C\n\x0freducer_request\x12\x18\n\x10reducer_function\x18\x01 \x01(\t\x12\x16\n\x06result\x18\x02 \x03(\x0b\x32\x06.tuple2\xaa\x01\n\x06Worker\x12\x31\n\nworker_map\x12\x0f.mapper_request\x1a\x10.mapper_response\"\x00\x12\x34\n\x10\x63onnect_to_store\x12\x08.address\x1a\x14.connection_response\"\x00\x12\x37\n\x0eworker_reducer\x12\x10.reducer_request\x1a\x11.reducer_response\"\x00\x62\x06proto3')
)




_MAPPER_REQUEST = _descriptor.Descriptor(
  name='mapper_request',
  full_name='mapper_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='mapper_request.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lines', full_name='mapper_request.lines', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map_function', full_name='mapper_request.map_function', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=88,
)


_TUPLE = _descriptor.Descriptor(
  name='tuple',
  full_name='tuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tuple.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='tuple.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=125,
)


_TUPLE_LIST = _descriptor.Descriptor(
  name='tuple_list',
  full_name='tuple_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='tuple_list.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=163,
)


_MAPPER_RESPONSE = _descriptor.Descriptor(
  name='mapper_response',
  full_name='mapper_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='mapper_response.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=206,
)


_ADDRESS = _descriptor.Descriptor(
  name='address',
  full_name='address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='address.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='address.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='address.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=257,
)


_CONNECTION_RESPONSE = _descriptor.Descriptor(
  name='connection_response',
  full_name='connection_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='connection_response.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=294,
)


_REDUCER_RESPONSE = _descriptor.Descriptor(
  name='reducer_response',
  full_name='reducer_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='reducer_response.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=338,
)


_REDUCER_REQUEST = _descriptor.Descriptor(
  name='reducer_request',
  full_name='reducer_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reducer_function', full_name='reducer_request.reducer_function', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='reducer_request.result', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=407,
)

_TUPLE_LIST.fields_by_name['result'].message_type = _TUPLE
_MAPPER_RESPONSE.fields_by_name['result'].message_type = _TUPLE
_REDUCER_RESPONSE.fields_by_name['result'].message_type = _TUPLE
_REDUCER_REQUEST.fields_by_name['result'].message_type = _TUPLE
DESCRIPTOR.message_types_by_name['mapper_request'] = _MAPPER_REQUEST
DESCRIPTOR.message_types_by_name['tuple'] = _TUPLE
DESCRIPTOR.message_types_by_name['tuple_list'] = _TUPLE_LIST
DESCRIPTOR.message_types_by_name['mapper_response'] = _MAPPER_RESPONSE
DESCRIPTOR.message_types_by_name['address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['connection_response'] = _CONNECTION_RESPONSE
DESCRIPTOR.message_types_by_name['reducer_response'] = _REDUCER_RESPONSE
DESCRIPTOR.message_types_by_name['reducer_request'] = _REDUCER_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mapper_request = _reflection.GeneratedProtocolMessageType('mapper_request', (_message.Message,), {
  'DESCRIPTOR' : _MAPPER_REQUEST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:mapper_request)
  })
_sym_db.RegisterMessage(mapper_request)

tuple = _reflection.GeneratedProtocolMessageType('tuple', (_message.Message,), {
  'DESCRIPTOR' : _TUPLE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:tuple)
  })
_sym_db.RegisterMessage(tuple)

tuple_list = _reflection.GeneratedProtocolMessageType('tuple_list', (_message.Message,), {
  'DESCRIPTOR' : _TUPLE_LIST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:tuple_list)
  })
_sym_db.RegisterMessage(tuple_list)

mapper_response = _reflection.GeneratedProtocolMessageType('mapper_response', (_message.Message,), {
  'DESCRIPTOR' : _MAPPER_RESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:mapper_response)
  })
_sym_db.RegisterMessage(mapper_response)

address = _reflection.GeneratedProtocolMessageType('address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:address)
  })
_sym_db.RegisterMessage(address)

connection_response = _reflection.GeneratedProtocolMessageType('connection_response', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTION_RESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:connection_response)
  })
_sym_db.RegisterMessage(connection_response)

reducer_response = _reflection.GeneratedProtocolMessageType('reducer_response', (_message.Message,), {
  'DESCRIPTOR' : _REDUCER_RESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:reducer_response)
  })
_sym_db.RegisterMessage(reducer_response)

reducer_request = _reflection.GeneratedProtocolMessageType('reducer_request', (_message.Message,), {
  'DESCRIPTOR' : _REDUCER_REQUEST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:reducer_request)
  })
_sym_db.RegisterMessage(reducer_request)



_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='Worker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=410,
  serialized_end=580,
  methods=[
  _descriptor.MethodDescriptor(
    name='worker_map',
    full_name='Worker.worker_map',
    index=0,
    containing_service=None,
    input_type=_MAPPER_REQUEST,
    output_type=_MAPPER_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='connect_to_store',
    full_name='Worker.connect_to_store',
    index=1,
    containing_service=None,
    input_type=_ADDRESS,
    output_type=_CONNECTION_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='worker_reducer',
    full_name='Worker.worker_reducer',
    index=2,
    containing_service=None,
    input_type=_REDUCER_REQUEST,
    output_type=_REDUCER_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
