# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import worker_pb2 as worker__pb2


class WorkerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.worker_map = channel.unary_unary(
        '/Worker/worker_map',
        request_serializer=worker__pb2.mapper_request.SerializeToString,
        response_deserializer=worker__pb2.mapper_response.FromString,
        )
    self.connect_to_store = channel.unary_unary(
        '/Worker/connect_to_store',
        request_serializer=worker__pb2.address.SerializeToString,
        response_deserializer=worker__pb2.connection_response.FromString,
        )
    self.worker_reducer = channel.unary_unary(
        '/Worker/worker_reducer',
        request_serializer=worker__pb2.reducer_request.SerializeToString,
        response_deserializer=worker__pb2.reducer_response.FromString,
        )


class WorkerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def worker_map(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def connect_to_store(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def worker_reducer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'worker_map': grpc.unary_unary_rpc_method_handler(
          servicer.worker_map,
          request_deserializer=worker__pb2.mapper_request.FromString,
          response_serializer=worker__pb2.mapper_response.SerializeToString,
      ),
      'connect_to_store': grpc.unary_unary_rpc_method_handler(
          servicer.connect_to_store,
          request_deserializer=worker__pb2.address.FromString,
          response_serializer=worker__pb2.connection_response.SerializeToString,
      ),
      'worker_reducer': grpc.unary_unary_rpc_method_handler(
          servicer.worker_reducer,
          request_deserializer=worker__pb2.reducer_request.FromString,
          response_serializer=worker__pb2.reducer_response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Worker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
